[package]
name = "tokenizers-ruby"
version = "0.1.0"
authors = ["Andrew Kane <andrew@ankane.org>"]
edition = "2018"
publish = false

[lib]
name = "tokenizers"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1"
rutie = "0.8.4"
tokenizers = "0.13.1"
